#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PRAXamForms.Droid.Resource", IsApplication=true)]

namespace PRAXamForms.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backImage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bubble = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fbIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int lkIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int prabh = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int PRATextBox = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int riyaz = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int twtIcon = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
